<script setup lang="ts">
import { unzipSync, strFromU8 } from 'fflate'

type Tab = 'today' | 'vocab' | 'news' | 'guide'
type Word = { id: string; word: string; phonetic: string; meaning: string; example: string; exampleCn: string; bookId: string; rank: number }
type NewsEntry = { id: string; title: string; url: string; level: string; date: string; firstListen: number; afterText: number; replay: number; vocabulary: string; recap: boolean; note: string }

const STORAGE_KEY = 'listening-desk-v1'
const tabs: { id: Tab; label: string; caption: string }[] = [
  { id: 'today', label: '今日计划', caption: '30 min' }, { id: 'vocab', label: '词汇工作台', caption: 'Anki' },
  { id: 'news', label: '听读记录', caption: '输入' }, { id: 'guide', label: 'Anki 入门', caption: '一步步' },
]
const sampleWords: Word[] = [
  { id: 'demo-retirement', word: 'retirement', phonetic: '/rɪˈtaɪəmənt/', meaning: 'n. 退休；退出', example: 'He announced his retirement from international football.', exampleCn: '他宣布退出国际足球比赛。', bookId: 'CET4-demo', rank: 1 },
  { id: 'demo-emotional', word: 'emotional', phonetic: '/ɪˈməʊʃənəl/', meaning: 'adj. 情绪激动的；有感染力的', example: 'It was an emotional moment for the fans.', exampleCn: '这对球迷来说是一个令人动容的时刻。', bookId: 'CET4-demo', rank: 2 },
  { id: 'demo-extraordinary', word: 'extraordinary', phonetic: '/ɪkˈstrɔːdənəri/', meaning: 'adj. 非凡的；特别的', example: 'She had an extraordinary career.', exampleCn: '她拥有一段非凡的职业生涯。', bookId: 'CET4-demo', rank: 3 },
  { id: 'demo-legacy', word: 'legacy', phonetic: '/ˈleɡəsi/', meaning: 'n. 遗产；留下的影响', example: 'His legacy will live on for many years.', exampleCn: '他的影响将延续很多年。', bookId: 'CET4-demo', rank: 4 },
  { id: 'demo-captain', word: 'captain', phonetic: '/ˈkæptɪn/', meaning: 'n. 队长；船长　v. 担任队长', example: 'She captained the team to victory.', exampleCn: '她带领球队取得了胜利。', bookId: 'CET4-demo', rank: 5 },
  { id: 'demo-commentator', word: 'commentator', phonetic: '/ˈkɒmənteɪtə(r)/', meaning: 'n. 评论员；解说员', example: 'The commentator described the final moments.', exampleCn: '解说员描述了最后的时刻。', bookId: 'CET4-demo', rank: 6 },
  { id: 'demo-era', word: 'era', phonetic: '/ˈɪərə/', meaning: 'n. 时代；年代', example: 'The player marked the end of an era.', exampleCn: '这名球员标志着一个时代的结束。', bookId: 'CET4-demo', rank: 7 },
  { id: 'demo-announce', word: 'announce', phonetic: '/əˈnaʊns/', meaning: 'v. 宣布；通知', example: 'The company announced a new plan.', exampleCn: '公司宣布了一项新计划。', bookId: 'CET4-demo', rank: 8 },
]

const activeTab = ref<Tab>('today')
const words = ref<Word[]>([])
const releasedCount = ref(100)
const newPerDay = ref(8)
const importMessage = ref('')
const importError = ref('')
const doneWords = ref<Record<string, string[]>>({})
const newsEntries = ref<NewsEntry[]>([])
const showAllWords = ref(false)
const newsForm = reactive({ title: '', url: '', level: 'Level 2', date: new Date().toISOString().slice(0, 10), firstListen: 10, afterText: 70, replay: 80, vocabulary: '', recap: false, note: '' })
const localStorageReady = ref(false)
const todayKey = new Date().toISOString().slice(0, 10)
const todayDone = computed(() => doneWords.value[todayKey] || [])
const curriculumWords = computed(() => words.value.slice(0, Math.min(releasedCount.value, words.value.length)))
const dayNumber = computed(() => {
  if (!localStorageReady.value) return 0
  const start = new Date(localStorage.getItem('listening-desk-start') || todayKey)
  const now = new Date(); start.setHours(0, 0, 0, 0); now.setHours(0, 0, 0, 0)
  return Math.max(0, Math.floor((now.getTime() - start.getTime()) / 86400000))
})
const todaysWords = computed(() => curriculumWords.value.slice(dayNumber.value * newPerDay.value, dayNumber.value * newPerDay.value + newPerDay.value))
const todayWordProgress = computed(() => todaysWords.value.filter(word => todayDone.value.includes(word.id)).length)
const minutesDone = computed(() => (todayWordProgress.value > 0 ? 10 : 0) + (newsEntries.value.some(entry => entry.date === todayKey) ? 12 : 0) + (newsEntries.value.some(entry => entry.date === todayKey && entry.recap) ? 8 : 0))
const completion = computed(() => Math.min(100, Math.round((minutesDone.value / 30) * 100)))
const recentEntries = computed(() => [...newsEntries.value].sort((a, b) => b.date.localeCompare(a.date)).slice(0, 6))
const average = (values: number[]) => values.length ? Math.round(values.reduce((sum, value) => sum + value, 0) / values.length) : 0
const averageFirstListen = computed(() => average(newsEntries.value.slice(0, 8).map(item => item.firstListen)))
const averageReplay = computed(() => average(newsEntries.value.slice(0, 8).map(item => item.replay)))

function persist() {
  if (!localStorageReady.value) return
  localStorage.setItem(STORAGE_KEY, JSON.stringify({ words: words.value, releasedCount: releasedCount.value, newPerDay: newPerDay.value, doneWords: doneWords.value, newsEntries: newsEntries.value }))
}
function markWord(word: Word) {
  const current = new Set(doneWords.value[todayKey] || [])
  if (current.has(word.id)) current.delete(word.id)
  else current.add(word.id)
  doneWords.value[todayKey] = [...current]; persist()
}
function parseWordLines(text: string, filename: string): Word[] {
  const clean = text.replace(/^\uFEFF/, '').trim()
  const raw: unknown[] = clean.startsWith('[') ? JSON.parse(clean) : clean.split(/\r?\n/).filter(Boolean).map(line => JSON.parse(line))
  return raw.map((value, index) => {
    const item = value as Record<string, unknown>
    const outerContent = (item.content || {}) as Record<string, unknown>
    const wordNode = (outerContent.word || {}) as Record<string, unknown>
    const content = (wordNode.content || {}) as Record<string, unknown>
    const translations = Array.isArray(content.trans) ? content.trans as Record<string, unknown>[] : []
    const sentenceNode = (content.sentence || {}) as Record<string, unknown>
    const sentences = Array.isArray(sentenceNode.sentences) ? sentenceNode.sentences as Record<string, unknown>[] : []
    const meaning = translations.map(translation => `${translation.pos ? `${translation.pos}. ` : ''}${translation.tranCn || translation.tranOther || ''}`).filter(Boolean).join('；')
    const firstSentence = sentences[0] || {}
    return { id: String(item.wordId || wordNode.wordId || `${item.bookId || filename}-${item.headWord}-${index}`), word: String(item.headWord || wordNode.wordHead || '').trim(), phonetic: String(content.usphone || content.ukphone || '').trim(), meaning: meaning || '暂无释义', example: String(firstSentence.sContent || '').trim(), exampleCn: String(firstSentence.sCn || '').trim(), bookId: String(item.bookId || filename.replace(/\.json$/i, '')), rank: Number(item.wordRank || index + 1) }
  }).filter(item => item.word)
}
async function readFile(file: File) {
  if (file.name.toLowerCase().endsWith('.zip')) {
    const archive = unzipSync(new Uint8Array(await file.arrayBuffer()))
    const entry = Object.entries(archive).find(([name]) => name.toLowerCase().endsWith('.json'))
    if (!entry) throw new Error('压缩包里没有找到 JSON 词书文件。')
    return parseWordLines(strFromU8(entry[1]), entry[0])
  }
  return parseWordLines(await file.text(), file.name)
}
async function importDictionary(event: Event) {
  const input = event.target as HTMLInputElement; const file = input.files?.[0]; if (!file) return
  importError.value = ''; importMessage.value = ''
  try { const imported = await readFile(file); const unique = new Map<string, Word>(); imported.forEach(item => unique.set(item.word.toLowerCase(), item)); words.value = [...unique.values()]; releasedCount.value = Math.min(100, words.value.length); importMessage.value = `已导入 ${words.value.length.toLocaleString()} 个词条，先释放 ${releasedCount.value} 个。`; persist(); activeTab.value = 'vocab' }
  catch (error: unknown) { importError.value = error instanceof Error ? error.message : '文件读取失败，请确认是词书 ZIP、JSON 或 NDJSON。' }
  finally { input.value = '' }
}
function loadDemo() { words.value = sampleWords; releasedCount.value = sampleWords.length; importMessage.value = '已载入 8 个演示词。你可以先体验完整流程，再导入真实词书。'; importError.value = ''; persist() }
function download(name: string, content: string, type = 'text/plain;charset=utf-8') { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type })); link.download = name; link.click(); URL.revokeObjectURL(link.href) }
function cleanTsv(value: string) { return value.replace(/[\t\r\n]+/g, ' ').trim() }
function exportAnki() { const header = ['#separator:Tab', '#html:true', '#columns:Word\tPhonetic\tMeaning\tExample\tExampleCN\tTags', '#deck:Listening Desk::CET4 Core', ''].join('\n'); const rows = curriculumWords.value.map(word => [word.word, word.phonetic, word.meaning, word.example, word.exampleCn, `dict-cet4 ${word.bookId}`].map(cleanTsv).join('\t')); download('listening-desk-cet4.tsv', `${header}${rows.join('\n')}\n`); importMessage.value = `已生成 ${rows.length} 张 Anki 卡片。` }
function saveNews() { if (!newsForm.title.trim()) return; newsEntries.value.unshift({ id: crypto.randomUUID(), ...newsForm, title: newsForm.title.trim(), vocabulary: newsForm.vocabulary.trim(), note: newsForm.note.trim() }); newsForm.title = ''; newsForm.url = ''; newsForm.vocabulary = ''; newsForm.note = ''; newsForm.recap = false; persist() }
function exportBackup() { download('listening-desk-backup.json', JSON.stringify({ version: 1, exportedAt: new Date().toISOString(), words: words.value, releasedCount: releasedCount.value, newPerDay: newPerDay.value, doneWords: doneWords.value, newsEntries: newsEntries.value }, null, 2), 'application/json;charset=utf-8') }
async function restoreBackup(event: Event) { const input = event.target as HTMLInputElement; const file = input.files?.[0]; if (!file) return; try { const data = JSON.parse(await file.text()); words.value = data.words || []; releasedCount.value = data.releasedCount || 100; newPerDay.value = data.newPerDay || 8; doneWords.value = data.doneWords || {}; newsEntries.value = data.newsEntries || []; persist(); importMessage.value = '备份已恢复。' } catch { importError.value = '备份文件不是有效的 JSON。' } input.value = '' }
onMounted(() => { localStorageReady.value = true; if (!localStorage.getItem('listening-desk-start')) localStorage.setItem('listening-desk-start', new Date().toISOString()); const saved = localStorage.getItem(STORAGE_KEY); if (saved) { try { const data = JSON.parse(saved); words.value = data.words || []; releasedCount.value = data.releasedCount || 100; newPerDay.value = data.newPerDay || 8; doneWords.value = data.doneWords || {}; newsEntries.value = data.newsEntries || [] } catch { /* start fresh */ } } })
watch([releasedCount, newPerDay], persist)
</script>

<template>
  <div class="app-shell">
    <header class="topbar"><div class="brand" @click="activeTab = 'today'"><div class="brand-mark"><span></span><span></span><span></span><span></span></div><div><strong>Listening Desk</strong><small>耳朵先行</small></div></div><div class="topbar-note">A2 → 更自在地听懂日常英语</div><button class="icon-button" title="导出本机备份" @click="exportBackup">↗</button></header>
    <main class="layout">
      <aside class="sidebar"><div class="eyebrow">YOUR ROUTE</div><nav><button v-for="tab in tabs" :key="tab.id" :class="['nav-item', { active: activeTab === tab.id }]" @click="activeTab = tab.id"><span>{{ tab.label }}</span><small>{{ tab.caption }}</small></button></nav><div class="sidebar-card"><span class="mini-label">本周听力信号</span><div class="signal"><i v-for="n in 10" :key="n" :class="{ lit: n <= Math.round((averageReplay || 10) / 10) }"></i></div><strong>{{ averageReplay || '—' }}%</strong><p>再次裸听理解率</p></div><div class="sidebar-footer">本地保存 · 零账号 · 零 API</div></aside>
      <section class="content">
        <div v-if="activeTab === 'today'" class="page enter"><div class="hero-grid"><div class="hero-copy"><div class="eyebrow warm">{{ todayKey }} · DAY {{ dayNumber + 1 }}</div><h1>今天，先让<br><em>耳朵认出</em>英语。</h1><p>阅读是地图，听力才是路。用 30 分钟，把声音和意义接在一起。</p><div class="hero-actions"><button class="primary" @click="activeTab = 'vocab'">开始今日词卡 <span>→</span></button><button class="text-button" @click="activeTab = 'news'">记录一条新闻</button></div></div><div class="progress-orbit"><div class="orbit-ring" :style="{ '--progress': `${completion}%` }"><div><strong>{{ completion }}<sup>%</sup></strong><span>今日完成</span></div></div><div class="orbit-note">声音<br>→ 意义</div></div></div><div class="section-heading"><div><div class="eyebrow">THE 30-MINUTE LOOP</div><h2>今天的三段路</h2></div><span class="muted">完成一段，就点亮一段</span></div><div class="plan-grid"><article class="plan-card" :class="{ done: todayWordProgress > 0 }"><div class="plan-index">01</div><div><h3>词卡热身</h3><p>复习到期卡片，再认识 {{ newPerDay }} 个新词。</p><div class="plan-meta"><span>{{ todayWordProgress }}/{{ todaysWords.length || newPerDay }} 已完成</span><button @click="activeTab = 'vocab'">去复习 →</button></div></div></article><article class="plan-card" :class="{ done: newsEntries.some(entry => entry.date === todayKey) }"><div class="plan-index">02</div><div><h3>听读一条新闻</h3><p>先裸听，再看文字，最后再次裸听。</p><div class="plan-meta"><span>12 MIN · LEVEL 2/3</span><button @click="activeTab = 'news'">记一条 →</button></div></div></article><article class="plan-card" :class="{ done: newsEntries.some(entry => entry.date === todayKey && entry.recap) }"><div class="plan-index">03</div><div><h3>60 秒口头概述</h3><p>说出主题、两个事实和你的看法。</p><div class="plan-meta"><span>20:00 以后</span><button @click="activeTab = 'news'">去记录 →</button></div></div></article></div><div class="lower-grid"><div class="quote-card"><div class="eyebrow warm">A SMALL PROMISE</div><blockquote>“不要等到听懂了才开口。<br>开口，是听懂的另一条路。”</blockquote><span>— 你的 12 周练习协议</span></div><div class="metric-card"><div class="eyebrow">YOUR SIGNAL</div><div class="metric-row"><div><strong>{{ averageFirstListen || '—' }}<small>%</small></strong><span>第一次裸听</span></div><div class="metric-arrow">→</div><div><strong>{{ averageReplay || '—' }}<small>%</small></strong><span>再次裸听</span></div></div><p>{{ averageFirstListen ? '最近记录显示，文本帮助你把声音的入口打开了。' : '记录第一条新闻后，这里会显示你的听力信号。' }}</p></div></div></div>
        <div v-else-if="activeTab === 'vocab'" class="page enter"><div class="page-title"><div><div class="eyebrow warm">VOCABULARY WORKBENCH</div><h1>词汇，不是终点。<br><em>是听力的扶手。</em></h1></div><div class="title-actions"><label class="secondary">导入词书<input type="file" accept=".zip,.json,.ndjson,.txt" @change="importDictionary"></label><button class="secondary" @click="loadDemo">先看演示</button></div></div><div v-if="importMessage" class="notice success">{{ importMessage }}</div><div v-if="importError" class="notice error">{{ importError }}</div><div class="import-card" v-if="!words.length"><div class="drop-icon">＋</div><div><h2>把 kajweb/dict 的词书拖进来</h2><p>支持 ZIP、JSON、NDJSON。应用会逐行解析、按词形去重，并先释放 100 个词。</p></div><label class="primary compact">选择文件<input type="file" accept=".zip,.json,.ndjson,.txt" @change="importDictionary"></label></div><div v-else><div class="control-strip"><div><span class="mini-label">当前词书</span><strong>{{ words[0]?.bookId || 'Imported dictionary' }}</strong><small>{{ words.length.toLocaleString() }} 个词条 · 已释放 {{ releasedCount }}</small></div><div class="release-control"><label>每日新词 <select v-model.number="newPerDay"><option :value="5">5</option><option :value="8">8</option><option :value="10">10</option></select></label><label>释放数量 <select v-model.number="releasedCount"><option :value="50">50</option><option :value="100">100</option><option :value="200">200</option><option :value="words.length">全部</option></select></label><button class="primary compact" @click="exportAnki">导出 Anki TSV</button></div></div><div class="word-list"><article v-for="word in (showAllWords ? curriculumWords : todaysWords)" :key="word.id" class="word-row" :class="{ checked: todayDone.includes(word.id) }"><button class="check" @click="markWord(word)">{{ todayDone.includes(word.id) ? '✓' : '' }}</button><div class="word-main"><strong>{{ word.word }}</strong><span>{{ word.phonetic || '—' }}</span></div><div class="word-meaning">{{ word.meaning }}</div><div class="word-example">{{ word.example || '导入数据没有例句' }}<small>{{ word.exampleCn }}</small></div></article></div><button class="show-more" @click="showAllWords = !showAllWords">{{ showAllWords ? '只看今日词卡 ↑' : `查看已释放的 ${curriculumWords.length} 个词 ↓` }}</button></div><div class="export-tip"><strong>导出后会发生什么？</strong><span>TSV 文件导入 Anki；Anki 负责间隔复习，卡片模板负责发音。这个工作台只负责挑词和记录学习。</span></div></div>
        <div v-else-if="activeTab === 'news'" class="page enter"><div class="page-title"><div><div class="eyebrow warm">LISTENING LOG</div><h1>让每一次<br><em>听不懂</em>留下线索。</h1></div><div class="title-note">先裸听，不要暂停。<br>记录比感觉可靠。</div></div><div class="news-layout"><form class="news-form" @submit.prevent="saveNews"><div class="form-section"><span class="mini-label">01 · 材料</span><label>标题<input v-model="newsForm.title" required placeholder="例如：Messi retires" /></label><label>原文 URL<input v-model="newsForm.url" type="url" placeholder="https://…" /></label><div class="form-inline"><label>级别<select v-model="newsForm.level"><option>Level 2</option><option>Level 3</option><option>影视 / 对话</option><option>其他</option></select></label><label>日期<input v-model="newsForm.date" type="date" /></label></div></div><div class="form-section"><span class="mini-label">02 · 三次听力</span><div class="range-line"><label>第一次裸听 <output>{{ newsForm.firstListen }}%</output><input v-model.number="newsForm.firstListen" type="range" min="0" max="100" /></label><label>看文本后 <output>{{ newsForm.afterText }}%</output><input v-model.number="newsForm.afterText" type="range" min="0" max="100" /></label><label>再次裸听 <output>{{ newsForm.replay }}%</output><input v-model.number="newsForm.replay" type="range" min="0" max="100" /></label></div></div><div class="form-section"><span class="mini-label">03 · 输出</span><label>查阅词汇<textarea v-model="newsForm.vocabulary" rows="2" placeholder="retirement, emotional…"></textarea></label><label>一句话自评<textarea v-model="newsForm.note" rows="2" placeholder="这次最卡的是连读 / 生词 / 语速…"></textarea></label><label class="toggle"><input v-model="newsForm.recap" type="checkbox" /><span></span>我在 20:00 后完成了 60 秒口头概述</label></div><button class="primary full" type="submit">保存这次听读 <span>→</span></button></form><div class="news-side"><div class="listening-rule"><div class="eyebrow warm">THE RULE</div><h2>听三次，<br>每次有不同任务。</h2><div class="rule"><b>1</b><span><strong>裸听</strong>只抓主题和人物，不追每个词。</span></div><div class="rule"><b>2</b><span><strong>看文本</strong>标出声音和文字没有对上的地方。</span></div><div class="rule"><b>3</b><span><strong>再裸听</strong>验证意义有没有留在耳朵里。</span></div></div><div class="recent-list"><div class="section-heading small"><h2>最近记录</h2><span>{{ newsEntries.length }} 条</span></div><div v-if="!recentEntries.length" class="empty">还没有记录。今晚听完第一条新闻，就从这里开始。</div><article v-for="entry in recentEntries" :key="entry.id" class="recent-item"><div><span>{{ entry.date }} · {{ entry.level }}</span><strong>{{ entry.title }}</strong></div><div class="mini-signal"><i v-for="n in 5" :key="n" :class="{ lit: n <= Math.ceil(entry.replay / 20) }"></i><b>{{ entry.replay }}%</b></div></article></div></div></div></div>
        <div v-else class="page enter guide-page"><div class="page-title"><div><div class="eyebrow warm">ANKI · FROM ZERO</div><h1>第一次使用，<br><em>照着走就好。</em></h1></div><div class="title-note">Mac 制卡<br>iPhone 复习</div></div><div class="guide-grid"><article class="guide-card"><div class="guide-number">01</div><h2>安装两个东西</h2><p>在 Mac 下载免费的 Anki Desktop；在浏览器注册免费的 AnkiWeb 账号。iPhone 暂时直接用 Safari 打开 AnkiWeb，不购买 AnkiMobile。</p><a href="https://apps.ankiweb.net/" target="_blank">打开 Anki 官网 ↗</a></article><article class="guide-card"><div class="guide-number">02</div><h2>导入这份 TSV</h2><p>回到“词汇工作台”，点击“导出 Anki TSV”。Anki Desktop 中选择 File → Import，选择文件，分隔符选 Tab，允许 HTML。</p><code>listening-desk-cet4.tsv</code></article><article class="guide-card"><div class="guide-number">03</div><h2>设置卡片模板</h2><p>字段顺序是 Word、Phonetic、Meaning、Example、ExampleCN、Tags。正面只放 Word，背面放其余字段。</p><div class="template"><span>&#123;&#123;Word&#125;&#125;</span><span>&#123;&#123;tts en_US:Word&#125;&#125;</span></div></article><article class="guide-card"><div class="guide-number">04</div><h2>打开 FSRS</h2><p>Deck Options → FSRS → Enable。目标记忆率先用 90%，新词每天 8 个。忘记时按 Again，不要按 Hard。</p><div class="rule-chip">Again = 忘了 · Good = 记得</div></article><article class="guide-card"><div class="guide-number">05</div><h2>同步到 iPhone</h2><p>Mac 点右上角 Sync，登录 AnkiWeb，第一次选择 Upload。iPhone Safari 登录同一账号，之后每天先 Sync 再复习。</p><a href="https://docs.ankiweb.net/syncing.html" target="_blank">查看同步说明 ↗</a></article><article class="guide-card"><div class="guide-number">06</div><h2>你的 30 分钟</h2><p>白天静默复习 10 分钟；晚上 8 点后听一条新闻、看文本、再裸听，最后做 60 秒概述。漏一天不补双倍新词。</p><div class="time-bars"><i></i><i></i><i></i></div></article></div><div class="backup-row"><div><strong>换设备前，先备份工作台</strong><span>词书和新闻记录保存在当前浏览器。Anki 卡片另由 AnkiWeb 同步。</span></div><button class="secondary" @click="exportBackup">导出 JSON 备份</button><label class="secondary">恢复备份<input type="file" accept=".json" @change="restoreBackup"></label></div></div>
      </section>
    </main>
  </div>
</template>

<style>
:root { --ink: #1d2533; --muted: #78818f; --line: #e5e7eb; --paper: #f7f8f5; --cream: #fffdf7; --orange: #ef6d45; --orange-dark: #c95735; --mint: #dff1e8; --navy: #24394b; --blue: #496b87; }
* { box-sizing: border-box; } html, body, #__nuxt { margin: 0; min-height: 100%; background: var(--paper); color: var(--ink); } body { font-family: Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, "Helvetica Neue", Arial, sans-serif; } button, input, textarea, select { font: inherit; } button, label { cursor: pointer; }
.app-shell { min-height: 100vh; background: radial-gradient(circle at 90% 0%, #fff5ed 0, transparent 33rem), var(--paper); }.topbar { height: 78px; display: flex; align-items: center; padding: 0 4vw; border-bottom: 1px solid var(--line); background: rgba(255,255,255,.72); backdrop-filter: blur(12px); position: sticky; top: 0; z-index: 5; }.brand { display: flex; align-items: center; gap: 12px; cursor: pointer; }.brand strong { display: block; font-family: Georgia, serif; font-size: 18px; letter-spacing: -.03em; }.brand small { display: block; color: var(--muted); font-size: 10px; letter-spacing: .16em; margin-top: 2px; }.brand-mark { width: 27px; height: 27px; display: flex; align-items: end; gap: 3px; padding: 4px; background: var(--orange); border-radius: 50%; }.brand-mark span { width: 3px; background: #fff8ef; border-radius: 4px; }.brand-mark span:nth-child(1) { height: 7px; }.brand-mark span:nth-child(2) { height: 14px; }.brand-mark span:nth-child(3) { height: 10px; }.brand-mark span:nth-child(4) { height: 17px; }.topbar-note { margin-left: auto; margin-right: 22px; color: var(--muted); font-size: 12px; }.icon-button { border: 0; background: transparent; font-size: 22px; color: var(--muted); padding: 8px; }.icon-button:hover { color: var(--orange); }
.layout { display: grid; grid-template-columns: 210px minmax(0, 1fr); max-width: 1440px; margin: auto; }.sidebar { min-height: calc(100vh - 78px); padding: 45px 24px 28px 4vw; border-right: 1px solid var(--line); display: flex; flex-direction: column; }.eyebrow, .mini-label { color: var(--muted); letter-spacing: .16em; font-size: 10px; font-weight: 700; }.eyebrow.warm { color: var(--orange); }.sidebar nav { margin-top: 20px; }.nav-item { width: 100%; border: 0; border-left: 2px solid transparent; background: transparent; color: var(--muted); text-align: left; display: flex; justify-content: space-between; align-items: baseline; padding: 12px 0 12px 12px; font-size: 13px; }.nav-item small { font-size: 10px; color: #aeb4bc; }.nav-item.active { color: var(--ink); border-left-color: var(--orange); font-weight: 700; }.sidebar-card { margin-top: auto; padding: 18px 0; border-top: 1px solid var(--line); }.sidebar-card strong { display: block; font-family: Georgia, serif; font-size: 31px; margin-top: 13px; }.sidebar-card p { color: var(--muted); font-size: 11px; margin: 2px 0 0; }.signal, .mini-signal { display: flex; align-items: end; height: 20px; gap: 3px; margin-top: 14px; }.signal i, .mini-signal i { display: block; width: 5px; height: 7px; border-radius: 3px; background: #dce1e4; }.signal i:nth-child(2n), .mini-signal i:nth-child(2n) { height: 12px; }.signal i:nth-child(3n), .mini-signal i:nth-child(3n) { height: 17px; }.signal i.lit, .mini-signal i.lit { background: var(--orange); }.sidebar-footer { color: #aab0b7; font-size: 10px; padding-top: 18px; }
.content { min-width: 0; padding: 54px clamp(24px, 5vw, 78px) 80px; }.page { max-width: 1070px; margin: auto; }.enter { animation: enter .35s ease both; } @keyframes enter { from { opacity: 0; transform: translateY(8px); } to { opacity: 1; transform: none; } }.hero-grid { display: grid; grid-template-columns: 1fr 310px; align-items: center; gap: 40px; min-height: 360px; }.hero-copy h1, .page-title h1 { font-family: Georgia, "Times New Roman", serif; font-weight: 400; letter-spacing: -.055em; line-height: .96; font-size: clamp(42px, 6vw, 76px); margin: 19px 0 22px; }.hero-copy h1 em, .page-title h1 em { color: var(--orange); font-style: italic; }.hero-copy p { max-width: 415px; color: var(--muted); line-height: 1.7; font-size: 14px; }.hero-actions { display: flex; align-items: center; gap: 20px; margin-top: 30px; }.primary, .secondary, .text-button { display: inline-flex; align-items: center; justify-content: center; gap: 12px; border-radius: 3px; padding: 12px 17px; font-weight: 700; font-size: 12px; transition: transform .2s, box-shadow .2s, background .2s; }.primary { border: 1px solid var(--orange); background: var(--orange); color: white; box-shadow: 0 8px 18px rgba(239,109,69,.18); }.primary:hover { transform: translateY(-2px); background: var(--orange-dark); }.primary.compact { padding: 10px 13px; }.primary.full { width: 100%; }.secondary { border: 1px solid #d7dce0; background: #fff; color: var(--ink); }.secondary:hover { border-color: var(--orange); color: var(--orange-dark); }.secondary input, .primary input { display: none; }.text-button { border: 0; background: transparent; color: var(--muted); padding-left: 0; }.text-button:hover { color: var(--orange); }
.progress-orbit { position: relative; display: flex; align-items: center; justify-content: center; min-height: 275px; }.orbit-ring { width: 222px; height: 222px; border-radius: 50%; display: grid; place-items: center; background: conic-gradient(var(--orange) var(--progress), #e7ece9 0); transform: rotate(-35deg); }.orbit-ring::before { content: ""; position: absolute; width: 178px; height: 178px; border-radius: 50%; background: var(--cream); }.orbit-ring > div { position: relative; z-index: 1; text-align: center; transform: rotate(35deg); }.orbit-ring strong { display: block; font-family: Georgia, serif; font-size: 45px; font-weight: 400; }.orbit-ring sup { color: var(--orange); font-size: 18px; }.orbit-ring span { display: block; color: var(--muted); font-size: 10px; letter-spacing: .12em; }.orbit-note { position: absolute; right: 0; bottom: 22px; color: var(--orange); font-size: 11px; line-height: 1.5; text-align: left; }
.section-heading { display: flex; justify-content: space-between; align-items: end; margin: 50px 0 18px; }.section-heading h2 { font-family: Georgia, serif; font-size: 28px; font-weight: 400; letter-spacing: -.04em; margin: 9px 0 0; }.muted, .section-heading.small > span { color: var(--muted); font-size: 12px; }.plan-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; }.plan-card { min-height: 190px; background: #fff; border: 1px solid var(--line); padding: 21px; display: grid; grid-template-columns: 32px 1fr; gap: 11px; position: relative; overflow: hidden; }.plan-card::after { content: ""; position: absolute; bottom: 0; left: 0; width: 0; height: 3px; background: var(--orange); transition: width .3s; }.plan-card.done::after { width: 100%; }.plan-index { color: var(--orange); font-family: Georgia, serif; font-style: italic; font-size: 18px; }.plan-card h3 { font-size: 15px; margin: 2px 0 8px; }.plan-card p { color: var(--muted); font-size: 12px; line-height: 1.6; margin: 0; min-height: 49px; }.plan-meta { display: flex; justify-content: space-between; align-items: center; margin-top: 17px; color: #9ca4ab; font-size: 9px; letter-spacing: .08em; }.plan-meta button { border: 0; padding: 0; color: var(--orange); background: transparent; font-size: 11px; font-weight: 700; }.lower-grid { display: grid; grid-template-columns: 1.1fr .9fr; gap: 12px; margin-top: 12px; }.quote-card, .metric-card { padding: 28px; min-height: 170px; }.quote-card { background: var(--navy); color: white; }.quote-card blockquote { font-family: Georgia, serif; font-size: 22px; line-height: 1.3; margin: 17px 0; letter-spacing: -.03em; }.quote-card span { color: #aebbc3; font-size: 11px; }.metric-card { background: var(--mint); }.metric-row { display: grid; grid-template-columns: 1fr 20px 1fr; align-items: center; margin-top: 25px; }.metric-row strong { font-family: Georgia, serif; font-size: 39px; font-weight: 400; }.metric-row strong small { color: var(--orange); font-size: 15px; }.metric-row span { display: block; color: #607b72; font-size: 10px; margin-top: 3px; }.metric-arrow { color: var(--orange); font-size: 20px; }.metric-card p { color: #607b72; font-size: 11px; margin: 20px 0 0; }
.page-title { display: flex; justify-content: space-between; align-items: end; margin-bottom: 34px; }.page-title h1 { font-size: clamp(40px, 5vw, 64px); margin-bottom: 0; }.title-actions, .title-note { display: flex; align-items: center; gap: 8px; color: var(--muted); font-size: 12px; line-height: 1.6; }.notice { padding: 12px 15px; margin-bottom: 15px; font-size: 12px; border-left: 3px solid; }.notice.success { background: var(--mint); border-color: #75ad93; color: #416c58; }.notice.error { background: #fff0ed; border-color: var(--orange); color: #9e4632; }.import-card { min-height: 150px; padding: 28px; display: flex; align-items: center; gap: 19px; border: 1px dashed #c8d0d2; background: rgba(255,255,255,.55); }.drop-icon { width: 40px; height: 40px; border-radius: 50%; display: grid; place-items: center; color: var(--orange); background: #ffede6; font-size: 23px; }.import-card h2 { font-family: Georgia, serif; font-weight: 400; font-size: 22px; margin: 0 0 6px; }.import-card p { color: var(--muted); font-size: 12px; margin: 0; }.import-card .primary { margin-left: auto; white-space: nowrap; }.control-strip { display: flex; align-items: center; justify-content: space-between; background: var(--navy); color: white; padding: 17px 20px; }.control-strip .mini-label { color: #aebbc3; }.control-strip strong { display: block; font-family: Georgia, serif; font-size: 20px; margin-top: 4px; }.control-strip small { color: #aebbc3; font-size: 11px; }.release-control { display: flex; align-items: center; gap: 8px; }.release-control label { color: #b8c3ca; font-size: 10px; }.release-control select { border: 1px solid #5c6d78; background: transparent; color: white; padding: 7px; margin-left: 5px; font-size: 11px; }.release-control option { color: var(--ink); }.word-list { margin-top: 12px; border-top: 1px solid var(--line); }.word-row { display: grid; grid-template-columns: 30px 1.1fr 1.4fr 2fr; align-items: center; gap: 15px; min-height: 76px; padding: 10px 13px; background: #fff; border-bottom: 1px solid var(--line); }.word-row.checked { background: #f3faf5; }.check { width: 21px; height: 21px; border-radius: 50%; border: 1px solid #cfd6d5; background: transparent; color: #fff; font-size: 12px; }.checked .check { border-color: #78a88e; background: #78a88e; }.word-main strong { display: block; font-family: Georgia, serif; font-size: 19px; font-weight: 400; }.word-main span { color: var(--orange); font-size: 11px; margin-top: 4px; display: block; }.word-meaning { font-size: 12px; line-height: 1.5; }.word-example { color: var(--blue); font-size: 11px; line-height: 1.5; }.word-example small { display: block; color: #a1a9ad; margin-top: 2px; }.show-more { border: 0; background: transparent; color: var(--orange); font-size: 12px; padding: 16px 0; }.export-tip { display: flex; gap: 12px; padding: 17px 0; border-top: 1px solid var(--line); color: var(--muted); font-size: 11px; line-height: 1.6; }.export-tip strong { color: var(--ink); white-space: nowrap; }
.news-layout { display: grid; grid-template-columns: minmax(0, 1.1fr) minmax(280px, .9fr); gap: 34px; }.news-form { background: #fff; border: 1px solid var(--line); padding: 25px; }.form-section { padding: 2px 0 23px; margin-bottom: 22px; border-bottom: 1px solid var(--line); }.form-section > .mini-label { display: block; color: var(--orange); margin-bottom: 17px; }.news-form label { display: block; color: var(--muted); font-size: 11px; margin-bottom: 13px; }.news-form input:not([type="range"]):not([type="checkbox"]), .news-form textarea, .news-form select { display: block; width: 100%; margin-top: 6px; border: 1px solid #dde1e2; border-radius: 2px; background: #fbfcfb; color: var(--ink); padding: 10px; font-size: 12px; outline: 0; }.news-form input:focus, .news-form textarea:focus, .news-form select:focus { border-color: var(--orange); }.form-inline { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }.range-line label { display: grid; grid-template-columns: 1fr auto; gap: 5px; align-items: center; }.range-line output { color: var(--orange); font-weight: 700; }.range-line input { grid-column: 1 / -1; width: 100%; accent-color: var(--orange); }.toggle { display: flex !important; align-items: center; gap: 8px; color: var(--ink) !important; }.toggle input { display: none; }.toggle span { width: 25px; height: 15px; border-radius: 10px; background: #dce1e2; position: relative; }.toggle span::after { content: ""; width: 11px; height: 11px; border-radius: 50%; background: #fff; position: absolute; top: 2px; left: 2px; transition: left .2s; }.toggle input:checked + span { background: var(--orange); }.toggle input:checked + span::after { left: 12px; }.listening-rule { background: var(--navy); color: white; padding: 27px; }.listening-rule .eyebrow { color: #ff9879; }.listening-rule h2 { font-family: Georgia, serif; font-size: 31px; font-weight: 400; line-height: 1; letter-spacing: -.04em; margin: 18px 0 28px; }.rule { display: grid; grid-template-columns: 29px 1fr; gap: 10px; align-items: start; padding: 13px 0; border-top: 1px solid #526570; color: #bac6cb; font-size: 11px; line-height: 1.5; }.rule b { color: #ff9879; font-family: Georgia, serif; font-size: 19px; font-weight: 400; }.rule strong { color: white; display: block; }.recent-list { margin-top: 31px; }.section-heading.small { margin: 0 0 13px; align-items: center; }.section-heading.small h2 { font-size: 21px; margin: 0; }.empty { color: var(--muted); font-size: 12px; line-height: 1.7; padding: 20px 0; }.recent-item { display: flex; justify-content: space-between; align-items: center; padding: 13px 0; border-top: 1px solid var(--line); }.recent-item span { display: block; color: var(--muted); font-size: 10px; }.recent-item strong { display: block; font-family: Georgia, serif; font-weight: 400; margin-top: 5px; }.mini-signal { height: 15px; margin: 0; }.mini-signal i { width: 4px; }.mini-signal b { margin-left: 6px; color: var(--orange); font-size: 11px; }
.guide-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; }.guide-card { background: #fff; border: 1px solid var(--line); padding: 22px; min-height: 210px; }.guide-number { color: var(--orange); font-family: Georgia, serif; font-style: italic; font-size: 18px; }.guide-card h2 { font-family: Georgia, serif; font-size: 20px; font-weight: 400; margin: 15px 0 9px; }.guide-card p { color: var(--muted); font-size: 12px; line-height: 1.65; margin: 0 0 15px; }.guide-card a { color: var(--orange); font-size: 11px; font-weight: 700; text-decoration: none; }.guide-card code, .template, .rule-chip { display: inline-block; background: #f4f5f3; color: var(--blue); padding: 8px 10px; font-size: 10px; }.template { display: grid; gap: 5px; }.rule-chip { color: #5e806e; background: var(--mint); }.time-bars { display: flex; gap: 4px; align-items: end; }.time-bars i { width: 20px; height: 10px; background: var(--orange); }.time-bars i:nth-child(2) { height: 16px; }.time-bars i:nth-child(3) { height: 23px; }.backup-row { margin-top: 14px; padding: 18px 20px; display: flex; align-items: center; gap: 8px; background: var(--mint); }.backup-row > div { margin-right: auto; }.backup-row strong, .backup-row span { display: block; }.backup-row strong { font-size: 13px; }.backup-row span { color: #607b72; font-size: 11px; margin-top: 4px; }.backup-row input { display: none; }
@media (max-width: 900px) { .layout { grid-template-columns: 1fr; }.sidebar { min-height: 0; padding: 14px 20px; border-right: 0; border-bottom: 1px solid var(--line); flex-direction: row; align-items: center; gap: 20px; }.sidebar .eyebrow, .sidebar-card, .sidebar-footer { display: none; }.sidebar nav { margin: 0; display: flex; flex: 1; gap: 2px; }.nav-item { border-left: 0; border-bottom: 2px solid transparent; padding: 9px 8px; display: block; }.nav-item.active { border-bottom-color: var(--orange); }.nav-item small { display: block; margin-top: 3px; }.content { padding: 35px 20px 60px; }.hero-grid { grid-template-columns: 1fr; min-height: 0; }.progress-orbit { display: none; }.plan-grid, .guide-grid { grid-template-columns: 1fr; }.lower-grid, .news-layout { grid-template-columns: 1fr; }.word-row { grid-template-columns: 28px 1fr; }.word-meaning, .word-example { grid-column: 2; }.word-example { display: none; }.control-strip { align-items: flex-start; gap: 15px; flex-direction: column; }.release-control { flex-wrap: wrap; }.page-title { align-items: flex-start; gap: 20px; flex-direction: column; }.title-actions { flex-wrap: wrap; }.backup-row { align-items: flex-start; flex-wrap: wrap; }.backup-row > div { flex-basis: 100%; margin-bottom: 4px; }.topbar-note { display: none; } }
@media (max-width: 520px) { .topbar { padding: 0 20px; }.nav-item { font-size: 11px; }.nav-item small { font-size: 9px; }.hero-copy h1, .page-title h1 { font-size: 47px; }.hero-actions { align-items: flex-start; flex-direction: column; gap: 10px; }.section-heading { align-items: flex-start; flex-direction: column; gap: 10px; }.import-card { align-items: flex-start; flex-direction: column; }.import-card .primary { margin-left: 0; }.export-tip { flex-direction: column; gap: 5px; }.form-inline { grid-template-columns: 1fr; } }
@media (prefers-reduced-motion: reduce) { *, *::before, *::after { animation-duration: .01ms !important; transition-duration: .01ms !important; } }
</style>
